### ISSUE TITLE
Could not build InfiniTime Firmware 1.6.0 with applied Watchfaces Modpack.

### ISSUE THREAD

**Issue by explit28** [ZephyrLabs/InfiniTime-Builder#1]
When i build 1.6.0 InfiniTime Firmware from Scratch - anything is fine, but if i apply a Watchface Modpack (Digistyle Watchface) - it begins to build, but the build process is interrupted with build error and new firmware files are not created. The error messages during build is to fast, so i can't read it.

Maybe you try to build 1.6.0 Infinitime Firmware with applied Digistyle Modpack ?

Thanks

**Comment by dtingley11** [comment]
its probably because you are using a newer version of infinitime. They made some changes in the code of the watch faces.

**Comment by explit28** [comment]
Is it possible to build 1.6.0 Infinitime with your watchfaces ?

**Comment by dtingley11** [comment]
I only changed one of the watch faces code. I had some help, however, but yes I can.

**Comment by explit28** [comment]
that would be awesome! i need only digistyle watchface. Thanks

**Comment by dtingley11** [comment]
I would actually go to the Pinetime discord server. They are better prepared to help update the watch faces

**Comment by dtingley11** [comment]
https://discord.gg/8uMhjXr5kE

**Comment by explit28** [comment]
ok thanks, will try

**Comment by explit28** [comment]
Any news on this issue ? Thanks

**Comment by ZephyrLabs** [comment]
@explit7 as @Appleisbest has said the code of the watchfaces as well certain makefile changes has rendered this modpack obsolete for the time, I will update asap, thanks for your cooperation :slightly_smiling_face:

**Comment by ZephyrLabs** [comment]
@explit7 here is an updated modpack for digistyle, hopefully I have packaged the right updated files, 
you can try testing to see if it works on your side, 

regd the sections where it says its building but finishes quickly, this may be due to a dependency issue, sometimes missing packages can cause this issue, I haven't gotten a way to catch the error yet, I plan to do some updates to this project, as better GUI tool :slightly_smiling_face:

[digistyle-Modpack.zip](https://github.com/ZephyrLabs/InfiniTime-Builder/files/7592703/digistyle-Modpack.zip)

**Comment by explit28** [comment]
Thanks, works like a charm now! You made my day!
The issue can safely be closed now.

**Comment by explit7** [comment]
I openened another issue, same Problem after update to InfiniTime 1.8.0 Can't add digistyle watchface. Thx!

**Comment by explit28** [comment]
Please see updated CMakeLists.txt for InfiniTime 1.8.0
